### PR TITLE
Tidy up pg_partman.md

### PR DESCRIPTION
**Pull request by IMSoP**
The formatting of the full manual page is rather broken on pgxn.org: http://pgxn.org/dist/pg_partman/doc/pg_partman.html

I'm not entirely sure what Markdown "flavour" they're using, but this patch makes the doc render nicely on both a GitHub Gist and http://daringfireball.net/projects/markdown/dingus so should hopefully be better.

### CODE REVIEW

**Comment by keithf4** [comment]
I've got a lot of changes to the doc file coming in the next version. Did you run pg_partman.md through some markdown tool or manually edit in all these changes?

**Comment by IMSoP** [comment]
I'm afraid I just manually edited it, so if you've got changes elsewhere they may or may not merge in cleanly. :(

The main changes are to the function and script options, which I've turned into proper sub-lists, because the fixed-width display was ugly-ish on GitHub, and completely broken on PGXN.

Other than that, it's mostly adding lots of backticks around commands, mostly because some Markdown parsers see foo_bar baz_quux as containing italics.

**Comment by keithf4** [comment]
Ok. I appreciate the work to do this, but I'm not going to be able to just merge it in because then all my changes would just overwrite what you've done unless I do them as well. I'll take a look at what you did and see if I can apply it to my version. Thanks!

**Comment by IMSoP** [comment]
Fair enough. Of course, if you shared your in-progress branch(es) to github rather than just master, I'd be able to try the merge myself... :)

**Comment by keithf4** [comment]
I did my best to include all your edits in the doc file for v2.0.0
If you see anything I missed, feel free to do another pull request :)

**Pull request closed without merging**
