### PR TITLE
Do some Python cleaning

### PR DESCRIPTION
**Pull request by rodo**
I ha a look at the python script and propose to do some cleaning before adding unit test. Do you find this usefull for you ?

A question after reading all the script, why is the `partman_version` differs in script ? Is it the minimal version of partman ? May be we can also rename it, `partman_minimal_version` ?

### CODE REVIEW

**Comment by keithf4** [comment]
Yes, partman_version & the --version argument are just for giving the minimal version of pg_partman needed. I mention this in the --help. 

Will look over the cleanup. Thanks!

**Comment by keithf4** [comment]
I've incorporated these changes into v2.6.2

If you'd like to create any unit tests for the python scripts, I'd definitely appreciate it!

**Comment by rodo** [comment]
If it's fixed in the current release, do I have to close my PR aor have you plan to merge it ?

**Comment by keithf4** [comment]
No need to merge, the code was copied into the release I did with some other fixes as well. If you want to close the issue, feel free, or I can close it.

**Comment by rodo** [comment]
Ok, fine !

**Pull request closed without merging**
