### PR TITLE
Partition by tsrange or tstzrange with a static bound

### PR DESCRIPTION
**Pull request by Trekoid**
With the refactor from #143 in place, the ability to partition using the bounds of a tsrange or a tstrange as mentioned in #142, has become easy to add. We have started using the attached changes internally at Porch.com to partition by the lower bound of a tstzrange data type column.

Others may want to partition by a static upper bound, so a complete feature implementation would be to add a parameter that would allow that to be configured. The case statement would end up looking like the following with a parameter added. The default for p_upper_range would be false, so that it would be an optional argument, providing backwards compatibility.

    v_partition_expression := case
        when v_epoch then format('to_timestamp(NEW.%I)', v_control)
        when v_ranged_control and p_upper_range then format('upper(NEW.%I)', v_control)
        when v_ranged_control and not p_upper_range then format('lower(NEW.%I)', v_control)
        else format('NEW.%I', v_control)
    end;

### CODE REVIEW

**Comment by Trekoid** [comment]
Having had a chance to step back, another approach would be to configure the partition expression based upon the data type of the control column. Instead of a boolean v_ranged_control variable, there would be a v_control_data_type variable. The data type of the control variable could be added to the configuration table when partitioning was initialized, so the select wouldn't have to be run in all of the functions.

    v_control_data_type    VARCHAR;
    
    SELECT data_type
    INTO v_control_data_type
    FROM information_schema.columns
    WHERE table_schema = v_parent_schema
    AND table_name = v_parent_tablename
    AND column_name = v_control;

    v_partition_expression := case
        -- integer and floating types that can be treated as epoch and converted using the to_timestamp function
        when v_control_data_type in ('smallint', 'integer', 'bigint'
                , 'decimal', 'numeric', 'real', 'double precision')
            then format('to_timestamp(NEW.%I)', v_control)
        when v_control_data_type in ('tsrange', 'tstzrange') and p_upper_range
            then format('upper(NEW.%I)', v_control)
        when v_control_data_type in ('tsrange', 'tstzrange') and not p_upper_range 
            then format('lower(NEW.%I)', v_control)
        when v_control_data_type in ('timestamp', 'timestamp with time zone', 'date')
            then format('NEW.%I', v_control)
        else
            raise error 'Unsupported data type detected'
    end;

**Comment by keithf4** [comment]
Any chance you could do this as another pull request with all the features you had in mind in a single commit (including the p_upper_range option)? Also without all the previous commits for the features added in 2.6.2? Hard to review the code like this.

**Comment by Trekoid** [comment]
Yes, I will create a new pull request. Wrapping projects before year end have had me tied up.

**Comment by keithf4** [comment]
v3.01 has been released and had quite a lot of internal code changes. If you'd still like to have this patch considered for inclusion, please see about consolidating the changes into a single commit as well as making sure they still work with the new major version. I've also changed pg_partman to automatically determine the partitioning type based on the control column's data type. So you may be able to reuse the one internal function I created (`check_control_type.sql`).

**Comment by Trekoid** [comment]
@keithf4 I will close this pull request and submit a new one based upon the current versioning. I have kept it open as a reminder to come back to this. I expect to be able to get to this next week.

**Comment by keithf4** [comment]
Ok. FYI, you may want to evaluate this against the native partitioning coming up in PG 10 as well. I believe its bounds are inclusive of the lower boundary and exclusive of the top.

**Comment by Trekoid** [comment]
I already have the attached working in 9.4 and 9.6 environments at work for the 2.6.2 version. I'm not sure when we will upgrade to 10 as it is taking forever for us to upgrade to 9.6.

The attached has been reworked and resubmitted against the 3.x changes in #183

**Pull request closed without merging**
