### PR TITLE
Parameterizing epoch logic

### PR DESCRIPTION
**Pull request by Trekoid**
What do you think of the following refactor that will eliminate the large duplicative code blocks for the epoch logic? It will significantly shrink the size of the time range functions and make the code easier to maintain. If this is acceptable, I will apply the same change to the rest of the `if v_epoch` conditionals.

### CODE REVIEW

**Comment by keithf4** [comment]
Very nice! Would prefer a more specifically named variable so it's clear what the expression is for. Something like `v_epoch_expression` or similar.

**Comment by Trekoid** [comment]
How about v_partition_expression which matches the existing v_partition_interval variable since they are both used for partition generation?

**Comment by keithf4** [comment]
Sounds good for now. Thanks!

**Comment by Trekoid** [comment]
I have refactored all of the relevant sections of create_function_time.sql and create_partition_time.sql. I am looking at partition_data_time.sql and undo_partition_time.sql. Both of those have instances of syntax like `to_timestamp(min(%I))`. Is it safe to swap the nesting to `min(to_timestamp(%I))` or is it written this way to take advantage of an optimization of the query planner?

I also did not want this PR to get so big it was a pain to review. If this is the case, I will hold until this portion has gone through the appropriate process.

**Comment by Trekoid** [comment]
I've been running some quick tests—caught a copy/paste error while I was at it—and determined that reversing the nesting is better for the min/max calls.

I did the following to test regular timestamps:

    CREATE TABLE test.time_taptest_table (col1 serial primary key
        , col2 text
        , col3 timestamp with time zone NOT NULL DEFAULT now());
    SELECT partman.create_parent('test.time_taptest_table', 'col3', 'time', 'daily');

    UPDATE partman.part_config 
        SET retention = '3 days'
      , retention_keep_table = false 
    WHERE parent_table = 'test.time_taptest_table';

    SELECT partman.run_maintenance();

    insert into test.time_taptest_table
    select 
       generate_series(1,1000) as col1
     , generate_series(1,1000)::text as col2
     , generate_series('2016-10-28 00:00:00-07'::timestamp with time zone
        , '2016-11-05 23:59:59.999-07'::timestamp with time zone
        , '0.009 days') as col3
    ;

I ran the following to test epochs, making sure to include the functional index as recommended in the documentation:

    create table test.epoch_taptest_table (col1 serial primary key
        , col2 text
        , col3 integer not null); -- default extract(epoch from now()));

    create index on test.epoch_taptest_table (to_timestamp(col3));

    select partman.create_parent('test.epoch_taptest_table', 'col3', 'time', 'daily', p_epoch := true);

    insert into test.epoch_taptest_table
    select 
       generate_series(1,1000) as col1
     , generate_series(1,1000)::text as col2
     , extract( epoch from generate_series('2016-10-28 00:00:00-07'::timestamp with time zone
        , '2016-11-05 23:59:59.999-07'::timestamp with time zone
        , '0.000009 days')) as col3
    ;

When I run an explain on:
1. `SELECT to_timestamp(min(col3)) FROM ONLY test.epoch_taptest_table_p2016_10_28;`
2. `SELECT min(to_timestamp(col3)) FROM ONLY test.epoch_taptest_table_p2016_10_28;`
The first one uses a table scan, while the second one ends up using the index.

**Comment by keithf4** [comment]
This is a busy week so haven't had a chance to really dig into your changes or test them. Just letting you know I appreciate all the work and will definitely get to it in the near future. :)

**Comment by Trekoid** [comment]
Thank you. I understand the prioritization.

I've done some sanity checking of my changes to the partition_data_time() and undo_partition_time(). I ran the following and the data all moved correctly:

    CREATE TABLE test.time_taptest_table (col1 serial primary key
        , col2 text
        , col3 timestamp with time zone NOT NULL DEFAULT now());

    insert into test.time_taptest_table
    select 
       generate_series(1,1000) as col1
     , generate_series(1,1000)::text as col2
     , generate_series('2016-10-28 00:00:00-07'::timestamp with time zone
        , '2016-11-05 23:59:59.999-07'::timestamp with time zone
        , '0.009 days') as col3
    ;

    SELECT partman.create_parent('test.time_taptest_table', 'col3', 'time', 'daily');

    select partman.partition_data_time('test.time_taptest_table');
    -- Ran 9 times with data, 10th returned 0

    select partman.undo_partition_time('test.time_taptest_table');
    -- Ran 9 times with data, 10th returned 0

The last bit of refactoring I see are the v_row.epoch if-else blocks in the run_maintenance() function.

**Comment by keithf4** [comment]
Once you've done you're refactoring, if you could make an extension update file, that would make it a lot easier to test and merge your changes in as well. See the `updates` folder for the example. Next version would be 2.6.2 since these are all internal patch changes. Should be able to just do simple  CREATE OR REPLACE calls for the functions as well since none have to be dropped & recreated.

**Comment by Trekoid** [comment]
Sanity tests for run_maintenance look good. I created a timestamp partition and an epoch partition each with a premake := 1. I inserted 1000 dummy rows into each partition set and ran run_maintenance() with no issues. Next, I updated the premake config to 3 for the timestamp partition, and run_maintenance successfully created the future partitions. Doing the same for the epoch partition with debugging on, yielded the following log:

    NOTICE:  run_maint: v_partition_expression: col3
    NOTICE:  run_maint: parent_table: test.time_taptest_table, v_last_partition: time_taptest_table_p2016_11_05
    NOTICE:  run_maint: v_current_partition_timestamp: 2016-11-02 00:00:00-07, v_max_time_parent: <NULL>
    NOTICE:  run_maint before loop: current_partition_timestamp: 2016-11-02 00:00:00-07, v_premade_count: 3, v_sub_timestamp_min: <NULL>, v_sub_timestamp_max: <NULL>
    NOTICE:  run_maint: v_partition_expression: to_timestamp(col3)
    NOTICE:  run_maint: parent_table: test.epoch_taptest_table, v_last_partition: epoch_taptest_table_p2016_11_03
    NOTICE:  run_maint: v_current_partition_timestamp: 2016-11-02 00:00:00-07, v_max_time_parent: <NULL>
    NOTICE:  run_maint before loop: current_partition_timestamp: 2016-11-02 00:00:00-07, v_premade_count: 1, v_sub_timestamp_min: <NULL>, v_sub_timestamp_max: <NULL>

    Total query runtime: 36 msec
    1 row retrieved.

    NOTICE:  run_maint: v_partition_expression: col3
    NOTICE:  run_maint: parent_table: test.time_taptest_table, v_last_partition: time_taptest_table_p2016_11_05
    NOTICE:  run_maint: v_current_partition_timestamp: 2016-11-02 00:00:00-07, v_max_time_parent: <NULL>
    NOTICE:  run_maint before loop: current_partition_timestamp: 2016-11-02 00:00:00-07, v_premade_count: 3, v_sub_timestamp_min: <NULL>, v_sub_timestamp_max: <NULL>
    NOTICE:  run_maint: v_partition_expression: to_timestamp(col3)
    NOTICE:  run_maint: parent_table: test.epoch_taptest_table, v_last_partition: epoch_taptest_table_p2016_11_03
    NOTICE:  run_maint: v_current_partition_timestamp: 2016-11-02 00:00:00-07, v_max_time_parent: <NULL>
    NOTICE:  run_maint before loop: current_partition_timestamp: 2016-11-02 00:00:00-07, v_premade_count: 1, v_sub_timestamp_min: <NULL>, v_sub_timestamp_max: <NULL>
    NOTICE:  run_maint: parent_table: test.epoch_taptest_table, v_premade_count: 1, v_next_partition_timestamp: 2016-11-03 00:00:00-07
    NOTICE:  run_maint: parent_table: test.epoch_taptest_table, v_premade_count: 2, v_next_partition_timestamp: 2016-11-04 00:00:00-07

    Total query runtime: 68 msec
    1 row retrieved.

I'll work on that extension update file.

**Comment by Trekoid** [comment]
I have added the update script, bumped versioning configs, and added a CHANGELOG note. I was able to successfully to upgrade the extension using the following:

    DROP EXTENSION pg_partman;

     CREATE EXTENSION pg_partman
      SCHEMA partman
      VERSION "2.6.1";

    ALTER EXTENSION pg_partman
      UPDATE TO "2.6.2";

I then proceeded to perform sanity checks and visually inspected the functions to verify the v_partition_expression variable existed.

Was there anything else you needed to help with the review?

**Comment by keithf4** [comment]
Not right now. If you can get pgtap installed to run the tests, that would be nice, but I will be doing that myself anyway. I'll hopefully be able to take a look at this next week. Thanks again!

**Comment by keithf4** [comment]
I've incorporated these changes into the 2.6.2 release.

Hadn't realized the positional option to the format() function to reused variables! Will have to remember that in the future and will simplify code elsewhere in this extension where I come across needing it. Thanks again!

**Comment by Trekoid** [comment]
Great news. You're welcome with the help.

**Pull request closed without merging**
