### PR TITLE
Separate foreign keys for a reference table by name.

### PR DESCRIPTION
**Pull request by adunstan**
Without this distinction, the code aggregates all the FKs refering to a
given table into a single FK, which is clearly wrong. Left for another
day is the task of adding the name to the constraint created on the
child.

Discovered on version 1.8.7, not sure how far back it needs to apply.

### CODE REVIEW

**Comment by keithf4** [comment]
Working on another large change at the moment. Will incorporate this change into 2.1.x and back-patch to 1.8.x. No need to go back any further.
Thanks!

**Comment by keithf4** [comment]
Can you give me an example table setup where this is true? I interpreted you scenario description as multiple foreign keys on the parent referencing the same table. But testing this out, I'm getting distinct results. (Modified the tables in the time-yearly test). I just want to really understand the issue before I go changing things in case there's an impact elsewhere.
```
Table "partman_test.fk_test_reference"
 Column | Type | Modifiers 
--------+------+-----------
 col2   | text | not null
 col4   | text | not null
Indexes:
    "fk_test_reference_col2_col4_idx" UNIQUE, btree (col2, col4)
    "fk_test_reference_col2_idx" UNIQUE, btree (col2)
Referenced by:
    TABLE "partman_test.time_taptest_table" CONSTRAINT "time_taptest_table_col2_fkey" FOREIGN KEY (col2, col4) REFERENCES partman_test.fk_test_reference(col2, col4) MATCH FULL ON DELETE RESTRICT DEFERRABLE
    TABLE "partman_test.time_taptest_table" CONSTRAINT "time_taptest_table_col2_fkey1" FOREIGN KEY (col2) REFERENCES partman_test.fk_test_reference(col2)
```
```
keith=# \d partman_test.time_taptest_table
          Unlogged table "partman_test.time_taptest_table"
 Column |           Type           |           Modifiers            
--------+--------------------------+--------------------------------
 col1   | integer                  | not null
 col2   | text                     | not null default 'stuff'::text
 col3   | timestamp with time zone | not null default now()
 col4   | text                     | not null default 'stuff'::text
Indexes:
    "time_taptest_table_pkey" PRIMARY KEY, btree (col1)
Foreign-key constraints:
    "time_taptest_table_col2_fkey" FOREIGN KEY (col2, col4) REFERENCES partman_test.fk_test_reference(col2, col4) MATCH FULL ON DELETE RESTRICT DEFERRABLE
    "time_taptest_table_col2_fkey1" FOREIGN KEY (col2) REFERENCES partman_test.fk_test_reference(col2)
Triggers:
    time_taptest_table_part_trig BEFORE INSERT ON partman_test.time_taptest_table FOR EACH ROW EXECUTE PROCEDURE partman_test.time_taptest_table_part_trig_func()
Number of child tables: 9 (Use \d+ to list them.)
```
Original query in current code now with result
```
keith=#     SELECT n.nspname||'.'||cl.relname AS ref_table
        , '"'||string_agg(att.attname, '","')||'"' AS ref_column
        , '"'||string_agg(att2.attname, '","')||'"' AS child_column
        , keys.condeferred
        , keys.condeferrable
        , keys.confupdtype
        , keys.confdeltype
        , keys.confmatchtype
    FROM
        ( SELECT unnest(con.conkey) as ref
                , unnest(con.confkey) as child
                , con.confrelid
                , con.conrelid
                , con.condeferred
                , con.condeferrable
                , con.confupdtype
                , con.confdeltype
                , con.confmatchtype
          FROM pg_catalog.pg_class c
          JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
          JOIN pg_catalog.pg_constraint con ON c.oid = con.conrelid
          WHERE n.nspname ||'.'|| c.relname = 'partman_test.time_taptest_table'
          AND con.contype = 'f'
          ORDER BY con.conkey
    ) keys
    JOIN pg_catalog.pg_class cl ON cl.oid = keys.confrelid
    JOIN pg_catalog.pg_namespace n ON cl.relnamespace = n.oid
    JOIN pg_catalog.pg_attribute att ON att.attrelid = keys.confrelid AND att.attnum = keys.child
    JOIN pg_catalog.pg_attribute att2 ON att2.attrelid = keys.conrelid AND att2.attnum = keys.ref
    GROUP BY n.nspname, cl.relname, keys.condeferred, keys.condeferrable, keys.confupdtype, keys.confdeltype, keys.confmatchtype
;
           ref_table            |  ref_column   | child_column  | condeferred | condeferrable | confupdtype | confdeltype | confmatchtype 
--------------------------------+---------------+---------------+-------------+---------------+-------------+-------------+---------------
 partman_test.fk_test_reference | "col2"        | "col2"        | f           | f             | a           | a           | s
 partman_test.fk_test_reference | "col2","col4" | "col2","col4" | f           | t             | a           | r           | f
(2 rows)
```

**Comment by keithf4** [comment]
Added another FK to the parent table to a different table all together. Still getting the results I expect
```
keith=# \d partman_test.fk_another_reference
Table "partman_test.fk_another_reference"
 Column | Type | Modifiers 
--------+------+-----------
 col2   | text | not null
 col4   | text | not null
Indexes:
    "fk_another_reference_col2_col4_idx" UNIQUE, btree (col2, col4)
    "fk_another_reference_col2_idx" UNIQUE, btree (col2)
    "fk_another_reference_col4_idx" UNIQUE, btree (col4)
Referenced by:
    TABLE "partman_test.time_taptest_table" CONSTRAINT "time_taptest_table_col4_fkey" FOREIGN KEY (col4) REFERENCES partman_test.fk_another_reference(col4)

keith=# \d partman_test.time_taptest_table
          Unlogged table "partman_test.time_taptest_table"
 Column |           Type           |           Modifiers            
--------+--------------------------+--------------------------------
 col1   | integer                  | not null
 col2   | text                     | not null default 'stuff'::text
 col3   | timestamp with time zone | not null default now()
 col4   | text                     | not null default 'stuff'::text
Indexes:
    "time_taptest_table_pkey" PRIMARY KEY, btree (col1)
Foreign-key constraints:
    "time_taptest_table_col2_fkey" FOREIGN KEY (col2, col4) REFERENCES partman_test.fk_test_reference(col2, col4) MATCH FULL ON DELETE RESTRICT DEFERRABLE
    "time_taptest_table_col2_fkey1" FOREIGN KEY (col2) REFERENCES partman_test.fk_test_reference(col2)
    "time_taptest_table_col4_fkey" FOREIGN KEY (col4) REFERENCES partman_test.fk_another_reference(col4)
Triggers:
    time_taptest_table_part_trig BEFORE INSERT ON partman_test.time_taptest_table FOR EACH ROW EXECUTE PROCEDURE partman_test.time_taptest_table_part_trig_func()
Number of child tables: 9 (Use \d+ to list them.)

             ref_table             |  ref_column   | child_column  | condeferred | condeferrable | confupdtype | confdeltype | confmatchtype 
-----------------------------------+---------------+---------------+-------------+---------------+-------------+-------------+---------------
 partman_test.fk_test_reference    | "col2"        | "col2"        | f           | f             | a           | a           | s
 partman_test.fk_test_reference    | "col2","col4" | "col2","col4" | f           | t             | a           | r           | f
 partman_test.fk_another_reference | "col4"        | "col4"        | f           | f             | a           | a           | s
(3 rows)
```
Also ran the python script to reapply to all children
```
bin/reapply_foreign_keys.py -p partman_test.time_taptest_table -c "host=localhost"

keith=# \d partman_test.time_taptest_table_p2011
       Unlogged table "partman_test.time_taptest_table_p2011"
 Column |           Type           |           Modifiers            
--------+--------------------------+--------------------------------
 col1   | integer                  | not null
 col2   | text                     | not null default 'stuff'::text
 col3   | timestamp with time zone | not null default now()
 col4   | text                     | not null default 'stuff'::text
Indexes:
    "time_taptest_table_p2011_pkey" PRIMARY KEY, btree (col1)
Check constraints:
    "time_taptest_table_p2011_partition_check" CHECK (col3 >= '2011-01-01 00:00:00-05'::timestamp with time zone AND col3 < '2012-01-01 00:00:00-05'::timestamp with time zone)
Foreign-key constraints:
    "time_taptest_table_p2011_col2_fkey" FOREIGN KEY (col2, col4) REFERENCES partman_test.fk_test_reference(col2, col4) MATCH FULL ON DELETE RESTRICT DEFERRABLE
    "time_taptest_table_p2011_col2_fkey1" FOREIGN KEY (col2) REFERENCES partman_test.fk_test_reference(col2)
    "time_taptest_table_p2011_col4_fkey" FOREIGN KEY (col4) REFERENCES partman_test.fk_another_reference(col4)
Inherits: partman_test.time_taptest_table
```

**Comment by adunstan** [comment]
example of the error generation below

```
partmantest=# create schema partman;
CREATE SCHEMA
partmantest=# create extension pg_partman with schema partman;
CREATE EXTENSION
partmantest=# create table foo (i int primary key);
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "foo_pkey" for table "foo"
CREATE TABLE                                                                    ^
partmantest=# create table bar (x serial primary key, y timestamptz not null, i int references foo(i), j int references foo(i));
NOTICE:  CREATE TABLE will create implicit sequence "bar_x_seq" for serial column "bar.x"
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "bar_pkey" for table "bar"
CREATE TABLE
partmantest=# select partman.create_parent('public.bar','y','time-static','weekly');
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "bar_p2015w24_pkey" for table "bar_p2015w24"
CONTEXT:  SQL statement "CREATE TABLE public.bar_p2015w24 (LIKE public.bar INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES INCLUDING STORAGE INCLUDING COMMENTS)"
PL/pgSQL function partman.create_partition_time(text,timestamp without time zone[],boolean) line 146 at EXECUTE statement
PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,boolean,text,boolean,boolean,boolean) line 260 at assignment
ERROR:  foreign key referenced-columns list must not contain duplicates
partmantest=# 
```

**Comment by adunstan** [comment]
The fix I came up with was quite minimal, but I think this whole query is probably misconceived. Why isn't it using pg_get_constraintdef(), which would surely make the code a tiny fraction of the size of this monster?

**Comment by keithf4** [comment]
Didn't know that function was available :)
I can take a look at it, or if you've got the time, I'd appreciate anything that makes the code more readable.

**Comment by adunstan** [comment]
I'd use something along the lines of

```sql
select conname, pg_get_constraintdef(oid) 
from pg_constraint 
where contype = 'f' 
   and conrelid = 'public.bar'::regclass;
```

Fill in the parent name appropriately

**Comment by keithf4** [comment]
Yep, I was just responding that I got it working. That does make it a whole lot easier. Looks like I can avoid all those conditionals as well to try and get the type of FK it is
```
keith=# select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'partman_test.time_taptest_table'::regclass and contype = 'f';
                                                  pg_get_constraintdef                                                   
-------------------------------------------------------------------------------------------------------------------------
 FOREIGN KEY (col2, col4) REFERENCES partman_test.fk_test_reference(col2, col4) MATCH FULL ON DELETE RESTRICT DEFERRABLE
(1 row)
```
And looks like it handles one worry I had as well since I'm now trying to support mixed case/special characters
```
keith=# alter table partman_test.fk_test_reference rename to "FK_test_Reference";
ALTER TABLE
keith=# select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'partman_test.time_taptest_table'::regclass and contype = 'f';
                                                   pg_get_constraintdef                                                    
---------------------------------------------------------------------------------------------------------------------------
 FOREIGN KEY (col2, col4) REFERENCES partman_test."FK_test_Reference"(col2, col4) MATCH FULL ON DELETE RESTRICT DEFERRABLE
(1 row)

```
Thanks!

**Comment by keithf4** [comment]
This has been fixed in version 2.1.0. Thanks for the bug report and simpler query!

**Pull request closed without merging**
