### PR TITLE
added limited upsert support

### PR DESCRIPTION
**Pull request by MikaelUlvesjo**
A patch for "PGSQL 9.5 UPSERT support on partitioned tables. #105"

### CODE REVIEW

**Comment by keithf4** [comment]
Very cool! Thanks for all the work. Been pretty busy lately, so won't have this ready to merge into the next version I'm already working on. Definitely want to look this over and get it in if possible in the near future, though.

**Comment by bk1te** [comment]
Hi any news on this issue?

**Comment by keithf4** [comment]
I do plan on integrating once I have the time to review it. However bug fixes are higher priority for me than new features, so working on those first.

**Comment by keithf4** [comment]
So, implemented your changes so far (which some modification) to the "upsert" branch. 

https://github.com/keithf4/pg_partman/tree/upsert

You can check it out to see my changes. One big thing I noticed was your examples were missing the DO UPDATE part of the ON CONFLICT clause. That was easy to fix. 

Bigger issue I've run into is with subpartitioning, which hadn't been handled either. You can see the issue in the `test-id-time-subpart-upsert-do-nothing.sql` test. I have it stop just after the error and leave things as they are in the database without rolling back. Because the date values are different, they go into different time sub-child tables, but allow duplication of the primary key value
```
keith@keith=# select * from partman_test.id_taptest_table_p10;
 col1 |  col2  |             col3              
------+--------+-------------------------------
   10 | «NULL» | 2016-07-07 18:17:10.858135-04
   11 | «NULL» | 2016-07-07 18:17:10.858135-04
   12 | «NULL» | 2016-07-07 18:17:10.858135-04
   13 | «NULL» | 2016-07-07 18:17:10.858135-04
   14 | «NULL» | 2016-07-07 18:17:10.858135-04
   15 | «NULL» | 2016-07-07 18:17:10.858135-04
   16 | «NULL» | 2016-07-07 18:17:10.858135-04
   17 | «NULL» | 2016-07-07 18:17:10.858135-04
   18 | «NULL» | 2016-07-07 18:17:10.858135-04
   19 | «NULL» | 2016-07-07 18:17:10.858135-04
   10 | «NULL» | 2016-07-08 18:17:08.299119-04
   11 | «NULL» | 2016-07-08 18:17:08.299119-04
   12 | «NULL» | 2016-07-08 18:17:08.299119-04
   13 | «NULL» | 2016-07-08 18:17:08.299119-04
   14 | «NULL» | 2016-07-08 18:17:08.299119-04
   15 | «NULL» | 2016-07-08 18:17:08.299119-04
   16 | «NULL» | 2016-07-08 18:17:08.299119-04
   17 | «NULL» | 2016-07-08 18:17:08.299119-04
   18 | «NULL» | 2016-07-08 18:17:08.299119-04
   19 | «NULL» | 2016-07-08 18:17:08.299119-04
(20 rows)

Time: 5.890 ms
keith@keith=# select * from partman_test.id_taptest_table_p10_p2016_07_07;
 col1 |  col2  |             col3              
------+--------+-------------------------------
   10 | «NULL» | 2016-07-07 18:17:10.858135-04
   11 | «NULL» | 2016-07-07 18:17:10.858135-04
   12 | «NULL» | 2016-07-07 18:17:10.858135-04
   13 | «NULL» | 2016-07-07 18:17:10.858135-04
   14 | «NULL» | 2016-07-07 18:17:10.858135-04
   15 | «NULL» | 2016-07-07 18:17:10.858135-04
   16 | «NULL» | 2016-07-07 18:17:10.858135-04
   17 | «NULL» | 2016-07-07 18:17:10.858135-04
   18 | «NULL» | 2016-07-07 18:17:10.858135-04
   19 | «NULL» | 2016-07-07 18:17:10.858135-04
(10 rows)

Time: 0.951 ms
keith@keith=# select * from partman_test.id_taptest_table_p10_p2016_07_08;
 col1 |  col2  |             col3              
------+--------+-------------------------------
   10 | «NULL» | 2016-07-08 18:17:08.299119-04
   11 | «NULL» | 2016-07-08 18:17:08.299119-04
   12 | «NULL» | 2016-07-08 18:17:08.299119-04
   13 | «NULL» | 2016-07-08 18:17:08.299119-04
   14 | «NULL» | 2016-07-08 18:17:08.299119-04
   15 | «NULL» | 2016-07-08 18:17:08.299119-04
   16 | «NULL» | 2016-07-08 18:17:08.299119-04
   17 | «NULL» | 2016-07-08 18:17:08.299119-04
   18 | «NULL» | 2016-07-08 18:17:08.299119-04
   19 | «NULL» | 2016-07-08 18:17:08.299119-04
(10 rows)

Time: 0.403 ms
```
Right now, I don't see any way around this since it's basically an issue with the core functionality of inheritance and the lack of global constraints. Only solution I can see right now is just not allowing the upsert option with subpartition sets. I've already limited other subpartition functionality, so I don't think this would be a huge deal. If you've got any ideas, I'd be glad to hear them.

**Comment by keithf4** [comment]
Actually, just realized after I posted this that that's an issue in general even without the UPSERT. But I think allowing the UPSERT option on subpartitioning would make it more confusing since the expected behaviour would be to not allow that at all.

**Comment by bk1te** [comment]
I think when developer uses specific features of database, like UPSERT, he is responsible of looking after constraints. Without upsert support in pg_partman there is no possibility to use it in specific applications. For now i am using PR in development...

**Comment by keithf4** [comment]
I'm all for getting the feature in, my worry is just with subpartitioning. UPSERT is entirely reliant on constraint management working a certain way and it seems a bit of a footgun with multiple-level inheritance getting involved since there's a higher expectation of things working a certain way.

Thinking I'm just not going to allow it to work with sub-partitioning for now so I can get the feature in and maybe down the line a better solution will come around.

**Comment by MikaelUlvesjo** [comment]
I was aware of the subpartition problem and that is why I added this with the header "limited upsert support". I agree with bk1te that if a developer uses functions like upsert he/she will have to know what they are doing, using the do update might be a problem with subpartition but do nothing function should work. BTW I'm sure that I wrote both do update and do nothing examples, I might have done that after the commit. I'm on vacation now and will not be able to check until the end of next week.

**Comment by MikaelUlvesjo** [comment]
Did not mean to close...

**Comment by keithf4** [comment]
You did write both examples. No worries there.

My example that failed with subpartitioning is actually a DO NOTHING example. It actually has nothing to do with the upsert feature at all. You can trigger the problem in the current version of pg_partman as well. My issue is the fact that someone going out of their way to use the upsert feature has a higher expectation of how constraints will be managed. Using upsert with multi-level inheritance is much more prone to issues since data will be getting written with the expectation that constraint violations will be handled in a specific way and, in all likelihood, they will not.

**Comment by keithf4** [comment]
Just thinking about this more, it's still a problem in single-level partitioning as well. If a table is partitioned by time and someone inserts the same primary key value again later that would put it in a different child, and it will allow that go go through without throwing an error. 

So, this only works for any constraint violations (not just primary keys) within each individual child table itself.  Data duplication can easily run rampant, but that can generally be handled by using the monitoring function I provide. However many DO UPDATE clauses for affected rows simply wouldn't fire at all. I'm really wondering how useful it actually is if conflicts are not handled across the entire partition set properly.

Have you all thought this out and accept that UPSERT simply does not work as intended with inheritance? I don't run anything in production where UPSERT is needed in a partitioned set, but you do. Going to be some major caveats on using this feature if implemented.

**Comment by MikaelUlvesjo** [comment]
I have tried it on a test environment but with real data stream, with id partitioning, both with do nothing and do update and in the do update case I did not change the id that is used in the partitioning only other data, and it worked perfectly, even with quite complicated do update queries where fields only where updated if the row in the db contained null and the conflicting row had a value. So I used it to do an update query and not a insert query when a conflict was detected, this way the application it self did not have to care if the new data was an update or an insert and this boosted the performance of the app quite a bit. The software I'm writing gets about 200 rows a second 24/7 so it is important that the performance and load on the system is not loading the system more then needed and that even when the table is locked for writing it will manage to insert all the data collected during that time fast so the queue don't build up over time.

**Comment by keithf4** [comment]
Ok. I'll see about getting it in. Just have to word the documentation carefully.

Thanks for the input!

**Comment by keithf4** [comment]
@MikaelUlvesjo @bk1te I've pushed another update out to the upsert branch

https://github.com/keithf4/pg_partman/tree/upsert

Can you please test this out and see if things work ok for you? Since the reasons it was failing with subpartitioning are the same shortcomings it has with normal partitioning, I didn't disable it there. Added some checks in to ensure the option is only usable in 9.5. Fixed some bugs encountered when running full pgtap test suite and updated the examples for more clarity.

Also would appreciate any feedback on the clarity of my explanations of the limitations upsert has with partitioning in the doc file.

Thanks!

**Comment by MikaelUlvesjo** [comment]
I looked at you commit and can't find anything in the code that I have any comments on.

In the documentation on ON CONFLICT DO UPDATE we might want to add a text that says something like this.

When using ON CONFLICT DO UPDATE it is important to NOT change the value that the partitioning is based on as the decision on what partition the data will be in is already taken and if changed to a value that belongs to another partition that row will end up in the wrong partition.

**Comment by keithf4** [comment]
Forgot about that. Thanks!

**Comment by keithf4** [comment]
I've released version 2.5.0 that incorporates this feature. Let me know if things are working ok.

**Comment by MikaelUlvesjo** [comment]
Latest release I can find is 2.4.1, did you forgot to do the actual release?

**Comment by keithf4** [comment]
I've pushed the code up. I usually ask the person who's feature/bug I added to check it out before I tag the release since it don't want to change things in a tagged release without releasing a new version.

**Comment by MikaelUlvesjo** [comment]
I have looked at the code any run it manually in my own test environment, but I can't test it on the test server without a real version that I can add to the build-scripts config.
You have my OK, i have done the testing I can.

**Comment by keithf4** [comment]
Version 2.5.0 tagged. Thanks!

**Pull request closed without merging**
